name: Update Calendar

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    permissions:  # 关键配置：显式声明写入权限
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # 禁用默认凭证

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run update script
        run: python update_calendar.py

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}  # 使用个人访问令牌（PAT）
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-Update: $(date +'%Y-%m-%d %H:%M')" --allow-empty
          git remote set-url origin "https://anduony:$GH_PAT@github.com/anduony/anduony.github.io.git"
          git push origin main
